DROP TABLE DIM_LIBRARY;
DROP TABLE DIM_BOOK;
DROP TABLE DIM_TIME;
DROP TABLE DIM_PATRON;

CREATE TABLE DIM_LIBRARY(ID NUMBER PRIMARY KEY, NAME VARCHAR(32) NOT NULL, CITY VARCHAR(32) NOT NULL, STATE VARCHAR(32) NOT NULL);
CREATE TABLE DIM_BOOK(ID NUMBER PRIMARY KEY, TITLE VARCHAR(32) NOT NULL, RATING NUMBER, author VARCHAR(32));
CREATE TABLE DIM_TIME(id NUMBER PRIMARY KEY, year NUMBER, month NUMBER, day NUMBER);
CREATE TABLE DIM_PATRON(id NUMBER PRIMARY KEY, CITY VARCHAR(32) NOT NULL, STATE VARCHAR(32) NOT NULL);

CREATE TABLE FACT_LEND(t NUMBER REFERENCES DIM_TIME(id), lib NUMBER REFERENCES DIM_LIBRARY(id), book NUMBER REFERENCES DIM_BOOK(id), 
                            patron REFERENCES DIM_PATRON(id), costs NUMBER, duration NUMBER);
